issuer: http://localhost:5556/

storage:
  type: sqlite3
  config:
    file: dex.db

web:
  http: localhost:5556

grpc:
  addr: localhost:5557

connectors:
  - type: mockCallback
    id: mock
    name: Example

enablePasswordDB: true